### ISSUE TITLE
Can we add calculating  calorie function?

### ISSUE THREAD

**Issue by JimmyZhangCN** [JimmyZhangCN/health_keeper#1]
## Why
I think calculating calorie is needed for us all.
## How
We can do it on the main page.

**Comment by SunnyJimmy** [comment]
I will do this feature.

**Comment by JimmyZhangCN** [comment]
Ok.This belongs to you.@SunnyJimmy

**Comment by JimmyZhangCN** [comment]
This issue is done by pull requset #2.
